---
language: node_js
node_js:
  - "8"
  - "9"
env:
  - CC=gcc-7 CXX=g++-7
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7
script: "npm run test"
